/**
 * Error code constants
 */

export const ErrorCodes = {
  // Parsing errors
  PARSING_SYNTAX_ERROR: 'SYNTAX_ERROR',
  PARSING_UNSUPPORTED_SYNTAX: 'UNSUPPORTED_SYNTAX',
  PARSING_INVALID_FILE: 'INVALID_FILE',

  // Validation errors
  VALIDATION_INVALID_CONFIG: 'INVALID_CONFIG',
  VALIDATION_MISSING_DEPENDENCY: 'MISSING_DEPENDENCY',
  VALIDATION_INCOMPATIBLE_VERSION: 'INCOMPATIBLE_VERSION',

  // Transformation errors
  TRANSFORMATION_FAILED: 'TRANSFORMATION_FAILED',
  TRANSFORMATION_UNSUPPORTED_PATTERN: 'UNSUPPORTED_PATTERN',
  TRANSFORMATION_CONFLICT: 'CONFLICT',

  // Configuration errors
  CONFIG_NOT_FOUND: 'NOT_FOUND',
  CONFIG_INVALID_FORMAT: 'INVALID_FORMAT',
  CONFIG_CONFLICT: 'CONFLICT',

  // File system errors
  FS_READ_ERROR: 'READ_ERROR',
  FS_WRITE_ERROR: 'WRITE_ERROR',
  FS_PERMISSION_DENIED: 'PERMISSION_DENIED',
  FS_NOT_FOUND: 'NOT_FOUND',
  FS_BACKUP_FAILED: 'BACKUP_FAILED'
} as const;
